services:
  vyomi-sql-postgres:
    ports: !override
      - "35432:5432"
  vyomi-sql-mysql:
    ports: !override
      - "33306:3306"
  vyomi-gcs:
    ports: !override
      - "34443:4443"
  vyomi-vault:
    ports: !override
      - "38200:8200"
  vyomi-minio:
    ports: !override
      - "39000:9000"
      - "39001:9001"
  vyomi-nats:
    ports: !override
      - "34222:4222"
  vyomi-dynamodb:
    ports: !override
      - "38000:8000"
  vyomi-elasticmq:
    ports: !override
      - "39324:9324"
  simulator:
    ports: !override
      - "${VYOMI_SIMULATOR_PORT:-9200}:9000"
    environment:
      CLOUDLEARN_DEV_MODE: "1"
      CLOUDLEARN_DISTRIBUTION_MODE: developer
    volumes:
      - ./tests:/app/tests:ro
      - ./server.py:/app/server.py:ro
      - ./core:/app/core:ro
      - ./providers:/app/providers:ro
      - ./routes:/app/routes:ro
      - ./static:/app/static:ro
