#!/usr/bin/env bash
# CloudLearn — laptop installer (curl-bash style).
#
# What it does:
#   1. Verifies Docker + Docker Compose v2 are present
#   2. Creates ~/.cloudlearn/{compose,data,deployments}  (no sudo)
#   3. Downloads docker-compose.yml + host config defaults from GitHub
#   4. Runs `docker compose up -d`  (4 services: simulator, cloudsim,
#      postgres, gcs — heavy backends provision lazily on first use)
#   5. Polls until /healthz responds, then opens the browser
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/sudhirkumarganti/cloud-learn/main/install.sh | bash
#
#   # With all 10 services eager (instead of lazy):
#   curl -fsSL ... | bash -s -- --full
#
#   # Pin a specific version:
#   curl -fsSL ... | bash -s -- --tag v0.1.0
#
#   # Just print what it would do without doing it:
#   curl -fsSL ... | bash -s -- --dry-run
#
# Re-running is safe — idempotent: existing volumes survive, only the
# compose file is re-downloaded.

set -euo pipefail

# ─── colours / formatting ───────────────────────────────────────────────
if [ -t 1 ] && command -v tput >/dev/null 2>&1; then
  B=$(tput bold) D=$(tput dim) R=$(tput sgr0)
  G=$(tput setaf 2) Y=$(tput setaf 3) C=$(tput setaf 6) M=$(tput setaf 5)
else
  B="" D="" R="" G="" Y="" C="" M=""
fi
ok()   { printf "  ${G}✓${R} %s\n" "$*"; }
warn() { printf "  ${Y}⚠${R} %s\n" "$*" >&2; }
err()  { printf "  ${R}${B}✗${R} %s\n" "$*" >&2; }
step() { printf "\n${B}${M}▶${R} ${B}%s${R}\n" "$*"; }

# ─── args ───────────────────────────────────────────────────────────────
PROFILE=""
DRY_RUN="0"
IMAGE_TAG=""
REPO_RAW="https://raw.githubusercontent.com/sudhirkumarganti/cloud-learn/main"

while [ $# -gt 0 ]; do
  case "$1" in
    --full)     PROFILE="full" ; shift ;;
    --dry-run)  DRY_RUN="1"    ; shift ;;
    --tag)      IMAGE_TAG="$2" ; shift 2 ;;
    --repo)     REPO_RAW="$2"  ; shift 2 ;;   # for forks / local testing
    -h|--help)
      sed -n '1,30p' "$0" | sed 's/^# *//'
      exit 0 ;;
    *)
      err "unknown flag: $1 (try --help)"
      exit 2 ;;
  esac
done

# ─── prereqs ────────────────────────────────────────────────────────────
step "Checking prerequisites"
if ! command -v docker >/dev/null 2>&1; then
  err "docker not found in PATH"
  echo "    Install Docker Desktop: https://docs.docker.com/get-docker/"
  exit 1
fi
ok "docker: $(docker --version | awk '{print $3}' | tr -d ,)"

if ! docker compose version >/dev/null 2>&1; then
  err "Docker Compose v2 not available (need 'docker compose', not 'docker-compose')"
  echo "    Update Docker Desktop to a recent version."
  exit 1
fi
ok "docker compose: $(docker compose version --short)"

if ! docker info >/dev/null 2>&1; then
  err "Docker daemon isn't running"
  echo "    Start Docker Desktop and re-run this script."
  exit 1
fi
ok "docker daemon reachable"

# ─── install dir ────────────────────────────────────────────────────────
CL_HOME="${CLOUDLEARN_HOME:-$HOME/.cloudlearn}"
step "Installing to ${B}${CL_HOME}${R}"
mkdir -p "$CL_HOME"/{compose,data,deployments,config}
ok "created $CL_HOME/{compose,data,deployments,config}"

# ─── fetch compose + host config defaults ───────────────────────────────
step "Downloading compose + config from GitHub"
DOWNLOAD() {
  local rel="$1" dest="$2"
  if [ "$DRY_RUN" = "1" ]; then
    echo "    (dry-run) would download $REPO_RAW/$rel → $dest"
    return
  fi
  if ! curl -fsSL -o "$dest" "$REPO_RAW/$rel"; then
    err "failed to download $rel"
    exit 1
  fi
  ok "downloaded $rel"
}
DOWNLOAD "docker-compose.yml"                           "$CL_HOME/compose/docker-compose.yml"
DOWNLOAD ".cloudlearn-host.json"                        "$CL_HOME/config/.cloudlearn-host.json"
DOWNLOAD ".cloudlearn-appliance/host-sizing-report.json" "$CL_HOME/config/host-sizing-report.json"

# ─── .env with the right paths ──────────────────────────────────────────
step "Generating .env"
ENV_FILE="$CL_HOME/compose/.env"
if [ -f "$ENV_FILE" ]; then
  ok ".env exists — not overwriting"
else
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Tweak any value and re-run \`docker compose up -d\` in this directory.

# Image tag — leave blank to use the compose default (:latest).
# Pin a version for production:
#   CLOUDLEARN_SIMULATOR_IMAGE=gansudkum/cloud-learn:0.1.0
${IMAGE_TAG:+CLOUDLEARN_SIMULATOR_IMAGE=gansudkum/cloud-learn:${IMAGE_TAG#v}}

# Host port for the simulator UI.
CLOUDLEARN_SIMULATOR_PORT=9000

# Where simulated cloud resources land on disk.
CLOUDLEARN_HOST_DEPLOY_DIR=$CL_HOME/deployments

# Distribution mode — leaves room for future enterprise/edge variants.
CLOUDLEARN_DISTRIBUTION_MODE=developer
EOF
  ok "wrote $ENV_FILE"
fi

# The compose file expects host config files at specific paths inside the
# compose-context dir; symlink the downloaded files in.
ln -sf "$CL_HOME/config/.cloudlearn-host.json"    "$CL_HOME/compose/.cloudlearn-host.json"
mkdir -p "$CL_HOME/compose/.cloudlearn-appliance"
ln -sf "$CL_HOME/config/host-sizing-report.json"  "$CL_HOME/compose/.cloudlearn-appliance/host-sizing-report.json"
ok "linked host config into compose context"

# Compose bind-mounts /var/lib/cloudlearn/deployments — redirect to
# user-owned dir so we don't need sudo.
mkdir -p "$CL_HOME/deployments"
if [ ! -d /var/lib/cloudlearn/deployments ]; then
  warn "/var/lib/cloudlearn/deployments doesn't exist (compose expects it)"
  echo "    The compose file maps it to a writable user dir via the .env:"
  echo "    CLOUDLEARN_HOST_DEPLOY_DIR is set, but compose still references"
  echo "    the absolute path. Either run once with sudo:"
  echo "      sudo mkdir -p /var/lib/cloudlearn/deployments && sudo chown $USER /var/lib/cloudlearn/deployments"
  echo "    Or accept that some deployment-export features won't write to disk."
fi

# ─── bring it up ────────────────────────────────────────────────────────
step "Starting the appliance"
COMPOSE_FLAGS=""
[ -n "$PROFILE" ] && COMPOSE_FLAGS="--profile $PROFILE"

if [ "$DRY_RUN" = "1" ]; then
  echo "    (dry-run) would run: cd $CL_HOME/compose && docker compose $COMPOSE_FLAGS pull"
  echo "    (dry-run) would run: cd $CL_HOME/compose && docker compose $COMPOSE_FLAGS up -d"
  exit 0
fi

cd "$CL_HOME/compose"
echo "    ${D}pulling images...${R}"
docker compose $COMPOSE_FLAGS pull 2>&1 | sed 's/^/    /'
echo "    ${D}starting containers...${R}"
docker compose $COMPOSE_FLAGS up -d 2>&1 | sed 's/^/    /'
ok "containers started"

# ─── wait for healthy ──────────────────────────────────────────────────
URL="http://localhost:${CLOUDLEARN_SIMULATOR_PORT:-9000}"
step "Waiting for $URL to respond"
for i in $(seq 1 60); do
  if curl -fsS --max-time 2 "$URL/healthz" >/dev/null 2>&1; then
    ok "ready after ${i}s"
    break
  fi
  sleep 1
  [ "$i" = "60" ] && { err "did not respond within 60s — check 'docker compose logs simulator'"; exit 1; }
done

# ─── open browser ───────────────────────────────────────────────────────
step "All set"
echo
echo "    ${G}${B}$URL${R}"
echo
echo "    Profile      : ${PROFILE:-default (4 services; rest lazy-provisioned)}"
echo "    Install dir  : $CL_HOME"
echo "    Compose dir  : $CL_HOME/compose"
echo
echo "    Useful commands (from $CL_HOME/compose):"
echo "      ${C}docker compose logs -f simulator${R}      tail logs"
echo "      ${C}docker compose down${R}                   stop everything"
echo "      ${C}docker compose pull && up -d${R}           upgrade to latest"
echo

# Try to open the browser (best-effort, ignore failures)
if command -v open >/dev/null 2>&1; then open "$URL" 2>/dev/null || true     # macOS
elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$URL" 2>/dev/null || true   # Linux
fi
