"""Generate the human-readable pass/fail matrix for the console
conformance suite. Writes a Markdown file CI can post as a PR
comment and devs can read locally.
"""
from __future__ import annotations
import collections
from typing import Any


def write_report(results: list[dict[str, Any]], path: str) -> dict[str, dict]:
    """Write Markdown report to `path`. Returns per-provider summary dict
    so the pytest summary hook can print rates."""
    by_provider_service: dict[tuple, list[dict]] = collections.defaultdict(list)
    by_provider: dict[str, dict] = collections.defaultdict(lambda: {"ok": 0, "total": 0})

    for r in results:
        key = (r["provider"], r["service"])
        by_provider_service[key].append(r)
        by_provider[r["provider"]]["total"] += 1
        if r["ok"]:
            by_provider[r["provider"]]["ok"] += 1

    lines = [
        "# Console actions — conformance report",
        "",
        "Auto-generated by `tests/conformance/console_actions/` on every run.",
        "Run locally: `pytest tests/conformance/console_actions/`",
        "",
        "## Pass-rate by provider",
        "",
        "| Provider | Pass | Total | Rate |",
        "|---|---|---|---|",
    ]
    for prov in sorted(by_provider.keys()):
        stats = by_provider[prov]
        rate = (stats["ok"] / stats["total"] * 100) if stats["total"] else 0
        flag = "✓" if rate == 100 else "✗"
        lines.append(f"| {flag} {prov} | {stats['ok']} | {stats['total']} | {rate:.1f}% |")
    lines.append("")

    # Per-service detail tables
    for prov in sorted(by_provider.keys()):
        lines.append(f"## {prov.upper()}")
        lines.append("")
        lines.append("| Service | Action | Method | Path | Status | Result |")
        lines.append("|---|---|---|---|---|---|")
        # Stable order — by service name, then action
        rows_for_prov = sorted(
            [r for r in results if r["provider"] == prov],
            key=lambda r: (r["service"], r["action"]),
        )
        for r in rows_for_prov:
            flag = "✓" if r["ok"] else "✗"
            reason = r.get("reason") or ""
            cell = f"{flag} {r['status_code']}"
            if reason:
                cell += f" — {reason[:80]}"
            lines.append(
                f"| `{r['service']}` | `{r['action']}` | `{r['method']}` | "
                f"`{r['path']}` | `{r['status_code']}` | {cell} |"
            )
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return dict(by_provider)
